### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by jonathonklem** [carbureted/react-native-pouchdb#1] opened 2016-03-25 04:15 UTC
I've installed react-native-sqlite before installing this package and I'm getting "SyntaxError react-native-pouchdb/pouchdb.js: Unexpected token (13530:0)".  I looked up the issue and in PhoneGap/Cordova, the remedy seems to be to use an es5 shim.  Is that what needs to be done with react-native applications as well?  I couldn't find anything about using any es5 shim with react-native.

**Comment by carbureted** [comment] 2016-03-25 11:07
Huh. I have not seen that. Anything weird about your environment? Are you on iOS on Android? Default babel/webpack config? React-native version?

**Comment by jonathonklem** [comment] 2016-03-25 12:28
Sorry about that.  No, I created the environment with the `react-native init` command and I haven't messed with babel/webpack.

Here's my package.json:

```
{
  "name": "TravelJournal",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "react": "^0.14.7",
    "react-native": "^0.22.2",
    "react-native-button": "^1.4.2",
    "react-native-checkbox": "^1.0.8",
    "react-native-facebook-login": "^1.0.3",
    "react-native-image-picker": "^0.18.3",
    "react-native-pouchdb": "0.0.3",
    "react-native-sqlite-storage": "^2.1.4"
  }
}
```

**Comment by jonathonklem** [comment] 2016-03-25 15:31
What's odd is I was able to pull a copy of the latest nightly build and use that to replace the pouchdb.js file that came with the npm package, and it's now working.

**Comment by carbureted** [comment] 2016-03-25 21:30
Pulled from pouchdb itself? In my experience, the main pouchdb package will work while dev tools are on and crash once you try to sync while in a production environment (see my comments at https://github.com/pouchdb/pouchdb/issues/4755). It would be awesome if that was no longer the case, though.

You're on a newer react-native version than me - I'll upgrade and see if I can reproduce your issue.

**Comment by jonathonklem** [comment] 2016-03-25 22:31
Sure enough, you're right.  It only worked locally if dev tools were on.  I tried applying the fix you mentioned in your comment to the latest version of PouchDB that I pulled, and the syntax error message didn't show up, however, I got a message about an unhandled promise rejection.

![image](https://cloud.githubusercontent.com/assets/4431712/14055365/5cb7ba48-f2af-11e5-9d15-82116a5d5d35.png)

**Comment by carbureted** [comment] 2016-03-25 23:12
Yeah, the version of pouchdb in this repo includes a shim for blobs, the various atob/btoa stuff, and forces pouchdb to always use fetch. Those should be the only major differences, so I'm not sure why this version is crashing for you. If you wanted to try adding the code from this [commit](https://github.com/carbureted/react-native-pouchdb/commit/0dada979eb598d82ca896a2c1f324575df848820) to the custom version you're using, you could see if that fixes your crash.

**Comment by jonathonklem** [comment] 2016-03-26 03:22
Thank you so much for the help!  That definitely fixed it.  Had you had an opportunity to check to see if upgrading your version of react-native broke things for you?  Some of this is a little over my head, but I notice that there's differences in whether or not "$1" is appended to various function names in the non-working version.  

I'm not sure if the problem is isolated to something weird with my environment, but this version of the code finally worked for me: 

https://gist.github.com/jonathonklem/99e0e4a8dd0dda359100

**Comment by carbureted** [comment] 2016-03-26 03:26
I haven't - react-native upgrades are often a pain point in my project. I've been intending to make an easily-upgradeable test repo for this and to write some tests for it, but I've been stretched a bit thin lately.

**Comment by jonathonklem** [comment] 2016-03-26 03:32
OK.  If you'd like I can submit my changes as a pull request.  It's working on my end, but I've only tested my changes in my environment.

**Comment by carbureted** [comment] 2016-03-29 18:37
It looks like the react-native team changed the config for the react-native packager in 0.22, which breaks a lot of modules, including Firebase and a bunch of modules I use. The easiest solution for me personally is probably going to be revert the config (it doesn't seem to be a lot of super important changes, just stuff like forcing strict mode on everything), but I'll try to bring this into compatibility soon. 

(First I need to get a test case going, though - I still haven't reproduced the specific issue you're seeing.)

**Comment by carbureted** [comment] 2016-03-30 02:32
Okay, I finished migrating to 0.22 - this package seems to be running fine. Hopefully upgrading this repo's pouch to 5.3.1 will fix your issue.

**Comment by jonathonklem** [comment] 2016-03-30 03:42
Thanks for everything.  It's working on my end.

**Comment by froatsnook** [comment] 2016-04-12 21:06
Hello.  I'm on react-native 0.23.1 and react-native-pouchdb 0.0.3.  I had the same SyntaxError!  Using your gist, @jonathonklem, fixed it (thank you!).  Is this package, as published, working for either of you?

**Comment by jonathonklem** [comment] 2016-04-12 22:01
@froatsnook I took it as an indicator that my setup was just odd (admittedly this is my first react-native project) and kept using the same code that was in the gist and didn't revert back to the original.

**Comment by carbureted** [comment] 2016-04-12 22:09
The package as published is working fine for me on 0.23.1, and I can't reproduce the error.

**Comment by froatsnook** [comment] 2016-04-12 22:13
Thanks for the quick replies!  Also my first react-native project, but I have a pretty basic setup so far.  The one thing that could be causing issues, I guess, is my babel config:

``` javascript
  "babel": {
    "env": {
      "native": {
        "presets": [
          "react-native-stage-0"
        ]
    ...
```

I don't even know if the node-haste packager is running babel on my node_modules though (this is why I want to use webpack).  What does your setup look like?

**Comment by carbureted** [comment] 2016-04-12 22:20
AFAIK I'm using all the default settings that are generated when using react-native init - I'll start looking into this again tonight, though.

**Comment by carbureted** [comment] 2016-04-13 06:05
Try out the new version and let me know if it fixes this for you.

**Comment by froatsnook** [comment] 2016-04-13 20:07
Looking good!

**Comment by froatsnook** [comment] 2016-04-13 20:08
By the way, thank you so much for sharing your work, @carbureted and @jonathonklem!  Saved me a ton of time.

**Comment by froatsnook** [comment] 2016-04-13 20:31
Are either of you using pouchdb-find?

**Comment by carbureted** [comment] 2016-04-13 20:43
Hope you don't mind if I close this?

I'm currently not, since I'm lucky enough not to have need of the pouchdb map/reduce API (my understanding is that it's slower than the other options). It looks much better than vanilla, though, so I kept it bookmarked.

**Closed as completed by carbureted** 2016-04-13 20:43 UTC
